vich_uploader:
    db_driver: orm

    mappings:
        img_presentation:
            uri_prefix: /images/presentation
            upload_destination: '%kernel.project_dir%/public/images/presentation'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        img_projet:
            uri_prefix: /images/projet
            upload_destination: '%kernel.project_dir%/public/images/projet'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
